/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface DIDRegistryInterface extends Interface {
    getFunction(nameOrSignature: "isRegistered" | "registerIssuer" | "resolveKey" | "rotateKey"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "IssuerRegistered" | "KeyRotated"): EventFragment;

    encodeFunctionData(functionFragment: 'isRegistered', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'registerIssuer', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'resolveKey', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'rotateKey', values: [BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'isRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerIssuer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rotateKey', data: BytesLike): Result;
  }

  
    export namespace IssuerRegisteredEvent {
      export type InputTuple = [didHash: BytesLike, controller: AddressLike];
      export type OutputTuple = [didHash: string, controller: string];
      export interface OutputObject {didHash: string, controller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace KeyRotatedEvent {
      export type InputTuple = [didHash: BytesLike, controller: AddressLike];
      export type OutputTuple = [didHash: string, controller: string];
      export interface OutputObject {didHash: string, controller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface DIDRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): DIDRegistry;
    waitForDeployment(): Promise<this>;

    interface: DIDRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    isRegistered: TypedContractMethod<
      [didHash: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    registerIssuer: TypedContractMethod<
      [didHash: BytesLike, pubKey: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    resolveKey: TypedContractMethod<
      [didHash: BytesLike, ],
      [string],
      'view'
    >
    

    
    rotateKey: TypedContractMethod<
      [didHash: BytesLike, newPubKey: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'isRegistered'): TypedContractMethod<
      [didHash: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'registerIssuer'): TypedContractMethod<
      [didHash: BytesLike, pubKey: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveKey'): TypedContractMethod<
      [didHash: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'rotateKey'): TypedContractMethod<
      [didHash: BytesLike, newPubKey: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'IssuerRegistered'): TypedContractEvent<IssuerRegisteredEvent.InputTuple, IssuerRegisteredEvent.OutputTuple, IssuerRegisteredEvent.OutputObject>;
getEvent(key: 'KeyRotated'): TypedContractEvent<KeyRotatedEvent.InputTuple, KeyRotatedEvent.OutputTuple, KeyRotatedEvent.OutputObject>;

    filters: {
      
      'IssuerRegistered(bytes32,address)': TypedContractEvent<IssuerRegisteredEvent.InputTuple, IssuerRegisteredEvent.OutputTuple, IssuerRegisteredEvent.OutputObject>;
      IssuerRegistered: TypedContractEvent<IssuerRegisteredEvent.InputTuple, IssuerRegisteredEvent.OutputTuple, IssuerRegisteredEvent.OutputObject>;
    

      'KeyRotated(bytes32,address)': TypedContractEvent<KeyRotatedEvent.InputTuple, KeyRotatedEvent.OutputTuple, KeyRotatedEvent.OutputObject>;
      KeyRotated: TypedContractEvent<KeyRotatedEvent.InputTuple, KeyRotatedEvent.OutputTuple, KeyRotatedEvent.OutputObject>;
    
    };
  }