/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DIDRegistry } from './DIDRegistry.js';
export type { StatusRegistry } from './StatusRegistry.js';
export * as factories from './factories/index.js';
export { StatusRegistry__factory } from './factories/StatusRegistry__factory.js';
export { DIDRegistry__factory } from './factories/DIDRegistry__factory.js';