/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface StatusRegistryInterface extends Interface {
    getFunction(nameOrSignature: "createStatusList" | "getListOwner" | "isRevoked" | "nextListId" | "revoke"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Revoked" | "StatusListCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'createStatusList', values?: undefined): string;
encodeFunctionData(functionFragment: 'getListOwner', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isRevoked', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextListId', values?: undefined): string;
encodeFunctionData(functionFragment: 'revoke', values: [BigNumberish, BigNumberish, string]): string;

    decodeFunctionResult(functionFragment: 'createStatusList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getListOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRevoked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextListId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revoke', data: BytesLike): Result;
  }

  
    export namespace RevokedEvent {
      export type InputTuple = [listId: BigNumberish, index: BigNumberish, reason: string];
      export type OutputTuple = [listId: bigint, index: bigint, reason: string];
      export interface OutputObject {listId: bigint, index: bigint, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StatusListCreatedEvent {
      export type InputTuple = [listId: BigNumberish, owner: AddressLike];
      export type OutputTuple = [listId: bigint, owner: string];
      export interface OutputObject {listId: bigint, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface StatusRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): StatusRegistry;
    waitForDeployment(): Promise<this>;

    interface: StatusRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createStatusList: TypedContractMethod<
      [],
      [bigint],
      'nonpayable'
    >
    

    
    getListOwner: TypedContractMethod<
      [listId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    isRevoked: TypedContractMethod<
      [listId: BigNumberish, index: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    nextListId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    revoke: TypedContractMethod<
      [listId: BigNumberish, index: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createStatusList'): TypedContractMethod<
      [],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getListOwner'): TypedContractMethod<
      [listId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isRevoked'): TypedContractMethod<
      [listId: BigNumberish, index: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'nextListId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'revoke'): TypedContractMethod<
      [listId: BigNumberish, index: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Revoked'): TypedContractEvent<RevokedEvent.InputTuple, RevokedEvent.OutputTuple, RevokedEvent.OutputObject>;
getEvent(key: 'StatusListCreated'): TypedContractEvent<StatusListCreatedEvent.InputTuple, StatusListCreatedEvent.OutputTuple, StatusListCreatedEvent.OutputObject>;

    filters: {
      
      'Revoked(uint256,uint256,string)': TypedContractEvent<RevokedEvent.InputTuple, RevokedEvent.OutputTuple, RevokedEvent.OutputObject>;
      Revoked: TypedContractEvent<RevokedEvent.InputTuple, RevokedEvent.OutputTuple, RevokedEvent.OutputObject>;
    

      'StatusListCreated(uint256,address)': TypedContractEvent<StatusListCreatedEvent.InputTuple, StatusListCreatedEvent.OutputTuple, StatusListCreatedEvent.OutputObject>;
      StatusListCreated: TypedContractEvent<StatusListCreatedEvent.InputTuple, StatusListCreatedEvent.OutputTuple, StatusListCreatedEvent.OutputObject>;
    
    };
  }