/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DIDRegistry__factory } from './DIDRegistry__factory.js';
export { StatusRegistry__factory } from './StatusRegistry__factory.js';